DELETE http://localhost:8080/events/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTczNjM1ODA5NywidXNlcklkIjoyfQ.GsWKLFZf5QuOG6W08TJXexwGx5vALBmWAj53lji6vVA