DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTczNjM1NzQ5NywidXNlcklkIjoyfQ.7pQU_tLbLMSeVRuKcIOOQMuk_qsAvgHgZ1k6sOD-YVM